language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

defore_deploy:
  - zip -r springboot-with-aws *
  - mkdir -p deploy
  - mv springboot-with-aws.zip deploy/springboot-with-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-with-aws-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-with-aws-build
    key: springboot-with-aws.zip
    bundle_type: zip
    application: springboot-with-aws # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: springboot-with-aws-group
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - hazxz@naver.com
